### ISSUE TITLE
please improve magnus man page

### ISSUE THREAD

**Issue by sunweaver** [stuartlangridge/magnus#8]
Hi,

your little project "magnus" has just been accepted to Debian unstable. The reviewing ftpmaster (master of the package archive) complained about the man page being extremely short.

Please improve it over time. Thanks!
Mike (aka sunweaver at debian.org)

**Comment by stuartlangridge** [comment]
https://github.com/stuartlangridge/magnus/commit/e488b7f69eb816fe6d849db7c95a36dd299171b9 hopefully adds enough detail to make the man page useful!

**Comment by alteholz** [comment]
Hi, 

thanks for providing such a tool.
It would be nice to explain how to set the zoom level. Just by calling magnus? And how to revert it back to normal again ...

   Thorsten

**Comment by stuartlangridge** [comment]
The zoom level is settable from the dropdown in the GUI; it's not settable from the command line. I don't think that man pages are meant to explain how to operate a GUI app, are they? If they are, I can add more to it to do that, but a man page doesn't seem a great match for that.

**Comment by alteholz** [comment]
Ah, ok, so maybe this could be a feature request?
Anyway, the man page should not explain everything but tell an unfamiliar user what this software does. For example the xpdf man page says: "xpdf - Portable Document Format (PDF) file viewer for X "
So everybody knows there are some cli options but a GUI is available as well.

**Comment by fossfreedom** [comment]
Brilliant news about Debian accepting this into their repos. Congrats @stuartlangridge :)

I look forward to promoting magnus through our distro Ubuntu Budgie soon ... hopefully a future v1.1 will land soon (budgie desktop specific fixes are in this repo but not in the current stable tagged release)?

**Comment by stuartlangridge** [comment]
All the credit for releases and getting magnus into Debian goes to @flexiondotorg rather than me. He's going to do a new point release relatively soon, I believe, which should contain the Budgie desktop fixes!

**Comment by sunweaver** [comment]
Hi,

On  Fr 02 Aug 2019 09:37:39 CEST, David Mohammed wrote:

> Brilliant news about Debian accepting this into their repos.  
> Congrats @stuartlangridge :)
>
> I look forward to promoting magnus through our distro Ubuntu Budgie  
> soon ... hopefully a future v1.1 will land soon (budgie desktop  
> specific fixes are in this repo but not in the current stable tagged  
> release)?

If ready, please release and I'll upload the new release to Debian ASAP.

Mike
-- 

DAS-NETZWERKTEAM
c\o Technik- und Ökologiezentrum Eckernförde
Mike Gabriel, Marienthaler str. 17, 24340 Eckernförde
mobile: +49 (1520) 1976 148
landline: +49 (4351) 850 8940

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by flexiondotorg** [comment]
Fixed via https://github.com/stuartlangridge/magnus/releases/tag/1.0.3
